---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-key
type: Opaque
data:
  id_rsa: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJsd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFZRUFvM3BUT3ZJSHNsTlRQVHdRVnVZMUNTYzhLMHpKY1AvZXYwdmVadHY0R2FJZmlveXB0WTV5Cml0SndNMzRwZmZjZWFEYkhRdTlzTms1cWhMNktGNWNNTkFrSTM3Wk4rSytlWkw3clRpMFoxanVIWkZGSnRCcGtIYXZHNDgKRzFnOHN4NmtoZzBzR004OG1CVEFtZ0RYVnAwQlpkREJpd3hzREpSSVROTHpuUDZVVDZFUm82SVRpcTNMUnEzWFNlNEVJWgpkczhpMkRQVzNQb09YZklndVpTUzZpYUVYV3IxNGZHckpjQXRxVlJsTk5meU42NEJ3MW1NR290TFZiVHV5RHJjbU5nZ0grCm03Yi9ST2hSS2RCalJMUTVMOUtFMFRpMERYSXZrY0sxZXVVVjE4aHNNT0JiTnNVRU5XN0J3bzlnSi9wRll3emZnQ21hYTIKb3RHTU5idUMvbXdHZFFGWmlhbGcyWWNuVTFHTXN1WDZTN29Tcm1ZRmhrNGlhYldudWlzcHVZaFFRZXgxbTZsYUJHYVd6VgpGRUlpcHpyMERhNU5lY1JaTk81MU1pektwZGN0RE44eVJlekRKL0pRUmF6YkhZeDN1VERCbUFwVW5uNEllL0hQNGdRcFJ3CkpXZFczTzV1d0d5MVdqRVpnUW9lWUJTS0FOZlpJSWtlekYwRkphNExBQUFGaUFReWJHTUVNbXhqQUFBQUIzTnphQzF5YzIKRUFBQUdCQUtONlV6cnlCN0pUVXowOEVGYm1OUWtuUEN0TXlYRC8zcjlMM21iYitCbWlINHFNcWJXT2NvclNjRE4rS1gzMwpIbWcyeDBMdmJEWk9hb1MraWhlWEREUUpDTisyVGZpdm5tUys2MDR0R2RZN2gyUlJTYlFhWkIycnh1UEJ0WVBMTWVwSVlOCkxCalBQSmdVd0pvQTExYWRBV1hRd1lzTWJBeVVTRXpTODV6K2xFK2hFYU9pRTRxdHkwYXQxMG51QkNHWGJQSXRnejF0ejYKRGwzeUlMbVVrdW9taEYxcTllSHhxeVhBTGFsVVpUVFg4amV1QWNOWmpCcUxTMVcwN3NnNjNKallJQi9wdTIvMFRvVVNuUQpZMFMwT1MvU2hORTR0QTF5TDVIQ3RYcmxGZGZJYkREZ1d6YkZCRFZ1d2NLUFlDZjZSV01NMzRBcG1tdHFMUmpEVzdndjVzCkJuVUJXWW1wWU5tSEoxTlJqTExsK2t1NkVxNW1CWVpPSW1tMXA3b3JLYm1JVUVIc2RadXBXZ1JtbHMxUlJDSXFjNjlBMnUKVFhuRVdUVHVkVElzeXFYWExRemZNa1hzd3lmeVVFV3MyeDJNZDdrd3daZ0tWSjUrQ0h2eHorSUVLVWNDVm5WdHp1YnNCcwp0Vm94R1lFS0htQVVpZ0RYMlNDSkhzeGRCU1d1Q3dBQUFBTUJBQUVBQUFHQUgvMjdOZWpST3NOMW9hRVViWDBGV2ZJMG95CkNXdHlkTFZ0SXBCcVg3U2tEZ3ZVTkRuc1R1ZzE0bEdONlNqaFVDL1UvaTlLVlgzdFMvb1pTTC80dk9sb3hDRVUxaXVzemIKU1VuWFVHZ2hDenlCQlUrbkJiaTRhTm9KeE41T2dDa09icE9WWndqN1pXWEVpTFhGZlh6QnBUZ0xJMmZkaURlSDY0RzFpWQoxZHMzK05GRFcydEhPYmRDOVdUbG9aRVRlK05mTFpGY2duUHYwc1BKUTZkVGF1L1dWbU44WExzbGlScm9TS0t2M2FCRnBTCkN6VmhJUEp3S1cyaTQzWFIySnN6Nmh5WkpoYjhDUEUxMFVPWUJEYnBvZXh6S0M0Y0Vlb08rWFV5U0N3d3UvZk1DSDhKUTcKQ1dGZWVxVHJHL2JkUy9FMFNBVllSYkRIU2sxbjlRaXhsTFVxMnUvNDUwKzc1ZWxENnNBUWtMV2JLc1A0eE4xMmZ4VXFLTQp2OWhIUEw1N3RNMm8zY3NsT2grRUZnMXRvNHRBaXkzTTVkK2V1T05XUzBpT04vSWxuZnkxU0Rqd1FpbkZGdHN3NHVCaFRjCjMvdkJBcWxMc25ibDZGWDBLL1M1UjduTTN4NVJaZ0VMK0x6RUIwN0Q4bEM4SVJlV2E1S1MzRFNqbFdZVHBsYkRHWkFBQUEKd0ZPRWpTcHY1UXFEOG5VS0Y3dFlTOUJLNldGYmdiZytFaFM5WmNEK0grU3pvcVM2NVhKU2t1dVZLY2E5SkhQUHhpOFVBTQpwWXUvQXlkREFsVHFMSGh6eXNocmNwSHhiS0haemZKMStySDNWWElSRDBpVk16ekloZy9xbCtFYTF5R0NTNnQvQUh5dlFHCmU0T0MxMXRlS25zR0FlWFc2SS8yU0oxYWY3eDc4Z0JGZ0RhaHZaOS9kUWdzZGxET3pyTkIxZjFXZFVkRm5GMU5vd3hNK1oKWENMMjRPSHUwOWFiaFVBL2N0T0JLdGtYK3hWSmxlbWZWZTNPREZ4TEhvRkZ2dWx3QUFBTUVBMEVtYWVPUDJGWDFXd2RscAowaVR6bjFPeFlQYzFmejdPb0p3OHRETlBycnRXRXJSQUppNGc5YjZ4WUNaVHRZdnM3WEs1WWxzZGJVOTN2NmZNWHF1WnltCjN2YzNPRXdqMXVMS1JlbHMveDJXRkNVY0xXOGVJMUNsRzNwbjd3UERYSjZ1YmRPU1BZa3AvNHNRRU9YZzcyc3ZmaTdaQjMKWUtSQ21yVmxRVEZWQXorbWczbVpjNm9HdlBjcVVIcjJTQnczNFZjQk1Ob2NBd3UzNDk1akZubHBqMkJWSmVxN3VzQzUyWApObFdHTkMzRTRQdTg3Q2RDZ2hUZVNKVlkvYjlMQ1ZBQUFBd1FESTdQNExKUEtSQ0lJa2tLbmdHdlowWmlpVEp1b0F5WXU0Ci9oK0lhenV1TGlNRG90SGtDT3Y0VmJ2cWRHSWxJZzllNDQzbFpyV3drWlg1ZE55aXRTam1ORTk0a28wWVVRM1VlOGZEbkkKWkxnK3ZaeHc5RTMzWDROTGdwMmt1dW9RZXNiaDNBZHZQWEk2VUt5Y05yZ2kwTWl4ZE00d1NYZGpkTldqMWxOaWNoTGM3agp1QXZhOVdzbVVqRWVYZjVxNC93VVpQMjFOUXpRbCtXOGdTV2E3dGV3bVBSYVV1eWh3ZE9RL3loWnRnVGxKWUd3QnBKYS9DCmpOYTZtMmxORmtIQjhBQUFBUmRHRnphR2xyYlc5cGJrQlVRVk5JU1VzQkFnPT0KLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==
# generate base64 key format with --> cat ~/.ssh/github | base64 -w0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-test-deploy-pipeline-sa
secrets:
  - name: github-ssh-key


---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-readme
spec:
  description: Read and display README file.
  workspaces:
  - name: source
  steps:
  - name: read
    image: alpine:latest
    script: | 
      #!/usr/bin/env sh
      cat $(workspaces.source.path)/README.md


---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-test-deploy-pipeline
spec:
  description: | 
    A CI workflow to continuously integrate and continuously deliver(stg) and continuously deploy a java spring microservice code to production environment.
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
    default: ssh://git@github.com/JohndoeWorkflow/Johndoe_Java_Microservice.git
  workspaces:
  - name: ssh-credentials
  - name: shared-data
    description: | 
      This workspace contains the cloned repo files, so they can be read by the
      next task.
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: ssh-directory
      workspace: ssh-credentials
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: show-readme
    runAfter: ["fetch-source"]
    taskRef:
      name: show-readme
    workspaces:
    - name: source
      workspace: shared-data