apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-test-deploy-pipeline-tb
spec:
  params:
  - name: URL
    value: ssh://git@github.com/JohndoeWorkflow/Johndoe_Java_Microservice.git   # it should come from event payload
  - name: REVISION
    value: xj35h23  # it should come from event payload
# to see complete payload data of github PR, visit, 
# https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#pullrequestevent
# https://github.com/gogs/gogs/issues/1573


---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: build-test-deploy-pipeline-tt
spec:

  params:
  - name: URL
    description: The repository url to build and deploy.
  - name: REVISION
    description: The revision or sha of the commit.

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-test-deploy-pipeline-pipelinerun-
    spec:
      serviceAccountName: build-test-deploy-pipeline-sa
      params:
      - name: repo-url
        value: ssh://git@github.com/JohndoeWorkflow/Johndoe_Java_Microservice.git
      - name: BUILDER_IMAGE
        value: gcr.io/kaniko-project/executor:v1.5.1
      - name: CONTEXT
        value: ./
      - name: DOCKERFILE
        value: /workspace/source/ 
      - name: IMAGE
        value: tashikmoin/johndoe-java-microservice:ki86nf
      pipelineRef:
        name: build-test-deploy-pipeline
      podTemplate:
        securityContext:
          fsGroup: 65532
          
      workspaces:
      - name: pipeline-secrets
        secret:
          secretName: pipeline-secrets
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi