apiVersion: v1
kind: Pod
metadata:
  name: kubectl
spec:
  volumes:
    - name: logs
      emptyDir: {}
  serviceAccountName: jenkins
  containers:
    - name: kubectl
      image: joshendriks/alpine-k8s
      command:
        - /bin/cat
      tty: true
      volumeMounts:
        - name: logs
          mountPath: /var/log
    - name: logger # the sidecar container tracking logs and sending them to stdout
      image: lutraman/logger-sidecar:v2
      volumeMounts:
        - name: logs
          mountPath: /logs
