apiVersion: v1
kind: Pod
metadata:
  name: builder
  namespace: jenkins
spec:
  serviceAccountName: jenkins
  containers:
    - name: enabler
      image: tashikmoin/tools
      tty: true
      stdin: true