apiVersion: v1
kind: Pod
metadata:
  name: kubectl
spec:
  serviceAccountName: jenkins
  containers:
    - name: kubectl
      image: yonadev/jnlp-slave-k8s-helm
      command:
        - /bin/cat
      tty: true
      stdin: true
      stdout: true
    - name: curl
      image: curlimages/curl
      command:
        - /bin/cat
      tty: true
      stdin: true
      stdout: true
