apiVersion: v1
kind: Pod
metadata:
  name: kubectl
spec:
  serviceAccountName: jenkins
  containers:
    - name: kubectl
      image: joshendriks/alpine-k8s
      command:
        - /bin/cat
      tty: true