apiVersion: v1
kind: Pod
metadata:
  name: agent-kubectl-curl
  namespace: jenkins
spec:
  serviceAccountName: jenkins
  containers:
    - name: kubectl
      image: yonadev/jnlp-slave-k8s-helm
      command:
        - /bin/cat
      tty: true
    - name: curl
      image: praqma/network-multitool
      tty: true
      stdin: true
      stdout: true
