apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-test-deploy-pipeline-pipelinerun-<COMMIT>
  namespace: default
spec:
  serviceAccountName: build-test-deploy-pipeline-sa
  params:
  - name: repo-url
    value: ssh://git@github.com/JohndoeWorkflow/Johndoe_Java_Microservice.git
  - name: BUILDER_IMAGE
    value: gcr.io/kaniko-project/executor:v1.5.1
  - name: CONTEXT
    value: ./
  - name: DOCKERFILE
    value: /workspace/source/ 
  - name: IMAGE
    value: tashikmoin/johndoe-java-microservice:<TAG>
  pipelineRef:
    name: build-test-deploy-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: pipeline-secrets
    secret:
      secretName: pipeline-secrets
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
