apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: johndoe-tb
spec:
  params:
  - name: url
    value: $(body.url)
  - name: revision
    value: $(body.revision)
  - name: build
    value: $(body.build)
  - name: dockerfile
    value: $(body.dockerfile)
  - name: context
    value: $(body.context)
  - name: image
    value: $(body.image)
  - name: imageBuilder
    value: $(body.imageBuilder)
  - name: pipelineName
    value: $(body.pipelineName)
  - name: environment
    value: $(body.environment)
    
# to see complete payload data of github PR, visit, 
# https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#pullrequestevent
# https://github.com/gogs/gogs/issues/1573


---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: johndoe-tt
spec:
  params:
  - name: url
    description: The repository url to build and deploy.
  - name: revision
    description: The revision or sha of the commit.
  - name: build
    description: build number
  - name: dockerfile
    description: path to dockerfile
  - name: context
    description: dockerfile build context/path relative to dockerfile path.
  - name: image
    description: service image name on registry
  - name: imageBuilder
    description: builder image name (docker, kaniko, etc)
  - name: pipelineName
    description: name of the pipeline
  - name: environment
    description: pipeline environment (dev, stg, prod)

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: "johndoe-pipelinerun-"
      labels:
        pipelineRunName: "johndoe-pipelinerun-$(tt.params.build)"
    spec:
      serviceAccountName: johndoe-sa
      params:
      - name: url
        value: "$(tt.params.url)"
      - name: build
        value: "$(tt.params.build)"
      - name: revision
        value: "$(tt.params.revision)"
      - name: imageBuilder
        value: "$(tt.params.imageBuilder)"
      - name: context
        value: "$(tt.params.context)"
      - name: dockerfile
        value: "$(tt.params.dockerfile)"
      - name: image
        value: "$(tt.params.image)"
      - name: environment
        value: "$(tt.params.environment)"
      pipelineRef:
        name: "$(tt.params.pipelineName)-$(tt.params.environment)"
      podTemplate:
        securityContext:
          fsGroup: 65532
      workspaces:
      - name: johndoe-secrets
        secret:
          secretName: johndoe-secrets
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
